[AssignmentSync]
type = drive
scope = drive
token = {"access_token":"ya29.a0AfH6SMCJzqPK6GqCFqZWhrx9hVNvVCDsTL_uVeAgCLNmOyZjW4DUMGW8aqWxTbHVQ4_dxgBMXaxQgwq3O0BABO6KxqLRA_9RHhn2kzszFxMTf4mjaI9AUbz-dxVAgOdM7PS1Gho_ttaNy40Y4M_KcsXC4nvisb5Fg4g","token_type":"Bearer","refresh_token":"1//0gRcQAoIWdodqCgYIARAAGBASNwF-L9IrlvrV1e8eAqe5R4Se2-Wvq-NSwXl_8tiZrbhTZHQ52V219TYW7lDL_GPd8bgzWQ59n4o","expiry":"2020-09-23T19:47:36.2175691+05:30"}
team_drive = 0AIkCYEURfAPlUk9PVA
root_folder_id = 

